### ISSUE TITLE
Doesn't install--cannot find go.mod file

### ISSUE THREAD

**Issue by sweth** [cutzenfriend/homebrew-cmdg#2]
==> Installing cmdg from cutzenfriend/cmdg
==> Downloading https://github.com/ThomasHabets/cmdg
Already downloaded: /Users/sweth/Library/Caches/Homebrew/downloads/0ee97fc66a2171fd746955b99cb0ad6cbcbc0cbf4b4390d94d92b05cfcd0068e--cmdg
Warning: Cannot verify integrity of '0ee97fc66a2171fd746955b99cb0ad6cbcbc0cbf4b4390d94d92b05cfcd0068e--cmdg'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "f9ff5c944990de130e8eb13959df217acc980631aca903fc431b50396f4fe675"
==> go build ./cmd/cmdg
Last 15 lines from /Users/sweth/Library/Logs/Homebrew/cmdg/01.go:
2021-04-28 10:56:38 -0500

go
build
./cmd/cmdg

go: go.mod file not found in current directory or any parent directory; see 'go help modules'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/cutzenfriend/homebrew-cmdg/issues

**Comment by cutzenfriend** [comment]
Fixed with v 1.4
